name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        pyv: ['3.9', '3.10', '3.11', '3.12', '3.13']
        include:
          - {os: ubuntu-latest, pyv: 'pypy3.9'}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.pyv }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyv }}
          allow-prereleases: true
          cache: 'pip'

      - name: Upgrade nox
        run: |
          python -m pip install --upgrade 'nox[uv]'
          nox --version

      - name: Lint code
        run: nox -s lint

      - name: Run tests
        run: nox -s tests-${{ matrix.pyv }} -- --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v5

      - name: Build package
        run: nox -s build
